# Generated by Django 3.1.2 on 2020-10-19 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='userName',
        ),
    ]
